changelog:
  exclude:
    labels:
      - bot
    authors:
      - renovate[bot]
  categories:
    - title: 🪄 Features & 🐛 Bugfixes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - github_actions
          - housekeeping
    - title: 🧹 Housekeeping
      labels:
        - housekeeping
