project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /lawnchair/res/values/strings.xml
    translation: /lawnchair/res/values-%android_code%/%original_file_name%
