name: Bug report
description: Create a report to help us address issues you are facing with the app.
title: "[BUG] "
labels: [ bug ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Ensure you are using the latest build.
      options:
        - label: No one has submitted a similar or identical bug report before.
          required: true
        - label: Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
