name: Question or Support Request
description: Ask a question or provide details of your support request here.
title: "[QUESTION] "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Note: We highly recommend posting your question/support request on either [Telegram](https://t.co/qYev4OkvpT) or [Discord](https://discord.com/invite/3x8qNWxgGZ). You'll recieve a quicker reply there.

        Before posting any question or ask for support, first read the README.md file and
        the [FAQ](https://lawnchair.app/faq) to see if you're question is listed there.
        
  - type: textarea
    id: question
    attributes:
      label: Describe your question or ask for support
      description: A clear and concise description of what your doubt is.
    validations:
      required: true
