name: Crowdin Download

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  synchronize-with-crowdin:
    name: Download translations from Crowdin
    if: github.repository_owner == 'LawnchairLauncher'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download translations
      uses: crowdin/github-action@v1
      with:
        upload_translations: false
        upload_sources: false
        download_translations: true
        localization_branch_name: 14-dev-localization
        create_pull_request: true
        base_url: 'https://lawnchair.crowdin.com'
      env:
        GITHUB_TOKEN: ${{ secrets.LAWNCHAIR_BOT_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
